# Generated by Django 5.1.4 on 2026-09-10 14:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Phone Verification',
                'verbose_name_plural': 'Phone Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TelegramPhoneLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True)),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(blank=True, default='', max_length=255)),
                ('chat_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram Phone Link',
                'verbose_name_plural': 'Telegram Phone Links',
                'ordering': ['-updated_at'],
            },
        ),
    ]
