# Generated by Django 5.1.4 on 2026-09-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tg_link_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_theme',
            field=models.CharField(choices=[('light', 'Light'), ('luxury', 'Luxury'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code', models.CharField(db_index=True, max_length=6)),
                ('purpose', models.CharField(default='register', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'purpose', 'is_used'], name='accounts_em_email_cd339c_idx')],
            },
        ),
    ]
