# Generated by Django 5.1.4 on 2026-08-26 10:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('max_orders_per_day', models.PositiveIntegerField(default=100)),
                ('delivery_radius_km', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('free_delivery_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_delivery_enabled', models.BooleanField(default=True)),
                ('is_pickup_enabled', models.BooleanField(default=True)),
                ('custom_message', models.TextField(blank=True, default='')),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='businesses.branch')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='businesses.business')),
            ],
            options={
                'verbose_name': 'Branch Settings',
                'verbose_name_plural': 'Branch Settings',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
