import os
from decouple import config

BOT_TOKEN = config('TELEGRAM_BOT_TOKEN', default='')
API_BASE_URL = config(
    'API_BASE_URL',
    default=f"http://localhost:{os.environ.get('PORT', '8000')}/api",
)

LOCALES = {
    'uz': {
        'welcome': "Business OS Bot ga xush kelibsiz!\n\nBiznesingizni boshqaring:",
        'help': " buyruqlari:\n\n/start - Boshlash\n/login - Tizimga kirish\n/dashboard - Boshqaruv paneli\n/orders - Buyurtmalar\n/sales - Sotuvlar\n/products - Mahsulotlar\n/stock - Ombor\n/lowstock - Kam qoldiq\n/notifications - Bildirishnomalar\n/logout - Chiqish\n/lang - Tilni o'zgartirish",
        'login_prompt': "Email manzilingizni kiriting:",
        'password_prompt': "Parolingizni kiriting:",
        'login_success': "Tizimga muvaffaqiyatli kirildi!",
        'login_failed': "Email yoki parol xato. Qayta urinib ko'ring.",
        'logout_success': "Tizimdan chiqildi.",
        'not_logged_in': "Avval tizimga kiring: /login",
        'dashboard_title': "Boshqaruv paneli",
        'today_sales': "Bugungi sotuvlar",
        'today_orders': "Bugungi buyurtmalar",
        'profit': "Foyda",
        'total_products': "Jami mahsulotlar",
        'low_stock': "Kam qoldiq",
        'no_data': "Ma'lumot topilmadi",
        'orders_title': "Buyurtmalar",
        'sales_title': "Sotuvlar",
        'products_title': "Mahsulotlar",
        'stock_title': "Ombor holati",
        'low_stock_title': "Kam qoldiq mahsulotlar",
        'notifications_title': "Bildirishnomalar",
        'no_notifications': "Bildirishnomalar yo'q",
        'lang_changed': "Til o'zgartirildi: O'zbek",
        'error': "Xatolik yuz berdi. Qayta urinib ko'ring.",
        'no_products': "Mahsulotlar topilmadi",
        'currency': "so'm",
        'linked_success': "Telegram hisobingiz sayt akkauntiga muvaffaqiyatli ulandi!",
        'link_failed': "Ulanish amalga oshmadi. Saytdan qayta urinib ko'ring.",
    },
    'ru': {
        'welcome': "Добро пожаловать в Business OS Bot!\n\nУправляйте бизнесом:",
        'help': " команды:\n\n/start - Начать\n/login - Войти\n/dashboard - Панель управления\n/orders - Заказы\n/sales - Продажи\n/products - Товары\n/stock - Склад\n/lowstock - Мало на складе\n/notifications - Уведомления\n/logout - Выйти\n/lang - Сменить язык",
        'login_prompt': "Введите ваш email:",
        'password_prompt': "Введите ваш пароль:",
        'login_success': "Вы успешно вошли в систему!",
        'login_failed': "Неверный email или пароль. Попробуйте снова.",
        'logout_success': "Вы вышли из системы.",
        'not_logged_in': "Сначала войдите: /login",
        'dashboard_title': "Панель управления",
        'today_sales': "Продажи сегодня",
        'today_orders': "Заказы сегодня",
        'profit': "Прибыль",
        'total_products': "Всего товаров",
        'low_stock': "Мало на складе",
        'no_data': "Данные не найдены",
        'orders_title': "Заказы",
        'sales_title': "Продажи",
        'products_title': "Товары",
        'stock_title': "Состояние склада",
        'low_stock_title': "Товары с малым запасом",
        'notifications_title': "Уведомления",
        'no_notifications': "Уведомлений нет",
        'lang_changed': "Язык изменён: Русский",
        'error': "Произошла ошибка. Попробуйте снова.",
        'no_products': "Товары не найдены",
        'currency': "сум",
        'linked_success': "Ваш Telegram успешно привязан к аккаунту на сайте!",
        'link_failed': "Не удалось привязать. Попробуйте ещё раз с сайта.",
    },
    'en': {
        'welcome': "Welcome to Business OS Bot!\n\nManage your business:",
        'help': " commands:\n\n/start - Start\n/login - Login\n/dashboard - Dashboard\n/orders - Orders\n/sales - Sales\n/products - Products\n/stock - Stock\n/lowstock - Low Stock\n/notifications - Notifications\n/logout - Logout\n/lang - Change language",
        'login_prompt': "Enter your email:",
        'password_prompt': "Enter your password:",
        'login_success': "Successfully signed in!",
        'login_failed': "Invalid email or password. Try again.",
        'logout_success': "You have been signed out.",
        'not_logged_in': "Please sign in first: /login",
        'dashboard_title': "Dashboard",
        'today_sales': "Today's Sales",
        'today_orders': "Today's Orders",
        'profit': "Profit",
        'total_products': "Total Products",
        'low_stock': "Low Stock",
        'no_data': "No data found",
        'orders_title': "Orders",
        'sales_title': "Sales",
        'products_title': "Products",
        'stock_title': "Stock Overview",
        'low_stock_title': "Low Stock Products",
        'notifications_title': "Notifications",
        'no_notifications': "No notifications",
        'lang_changed': "Language changed: English",
        'error': "An error occurred. Try again.",
        'no_products': "No products found",
        'currency': "UZS",
        'linked_success': "Your Telegram has been linked to your website account!",
        'link_failed': "Linking failed. Please try again from the website.",
    },
}


def t(key: str, lang: str = 'uz') -> str:
    return LOCALES.get(lang, LOCALES['uz']).get(key, LOCALES['uz'].get(key, key))
