# Generated by Django 5.1.4 on 2026-08-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_businesssettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='delivery_enabled',
            field=models.BooleanField(default=False, help_text='Enable delivery for this store'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery fee in UZS', max_digits=12),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Show store on public marketplace'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='min_order_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum order for delivery', max_digits=12),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='store_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='store_description',
            field=models.TextField(blank=True, default='', help_text='Public store description'),
        ),
        migrations.AddField(
            model_name='businesssettings',
            name='store_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
