# Generated by Django 5.1.4

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_add_marketplace_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssettings',
            name='store_name',
            field=models.CharField(blank=True, default='', help_text='Public store name shown in the marketplace', max_length=255),
        ),
    ]