# Generated by Django 5.1.4 on 2026-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_businesssettings_store_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='logo',
            field=models.TextField(blank=True, default=''),
        ),
    ]
